kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spark
  namespace: icteam
rules:
  - verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    apiGroups: [""]
    resources: ["pods", "configmaps", "services"]